name: AI CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04  # ✅ Đã sửa lỗi version image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'  # Sử dụng phiên bản cụ thể thay vì 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mlflow

      - name: Run tests
        run: python test_model.py

      - name: Train model
        run: python train.py

      - name: Select best model with AI Agent
        run: python agents/model_selector_agent.py